### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by Vdragon** [jsbin/reports#120]
Bin url: http://jsbin.com/yademece/1/

This bin simply draws a chart of the number of [COSCUP 2014](http://coscup.org/2014/en/) conference successfully registered attendees over time after the register is opened on [Registrano(Currently called KKTIX) event managing service](https://kktix.com/?locale=en).

![image](https://cloud.githubusercontent.com/assets/1192163/6829996/fbafe356-d351-11e4-9a24-7641f4d36cf8.png)

COSCUP is the biggest open-source software related conference in Taiwan, 700~1000 free attendee tickets were sold out in 47 seconds in 2013, and booked out in 10 seconds in 2014.

While this code is resource consuming on drawing all the data dots to the chart, it is not malicious.

**Comment by remy** [comment]
Fixed.
