### ISSUE TITLE
Incorrect reported bin

### ISSUE THREAD

**Issue by mihai-vlc** [jsbin/reports#129]
I can't use this url on facebook: http://jsbin.com/pecebo/edit?html,js,output

**Comment by remy** [comment]
The bin is not reported. Facebook have blocked sharing of JS Bin links. I suggest you report this as an error to FB, I know others are too.

**Comment by eeue56** [comment]
How do we go about reporting this to Facebook? I've been hit with this issue a couple of times and resorted to exporting things as gists in order to share.

**Comment by remy** [comment]
As in...Facebook is blocking it, and you're asking me how do we report to
Facebook? If that's the question...I have no idea.
