### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by AngerElf** [jsbin/reports#21]
Bin url: http://jsbin.com/xagax/2/edit

How and why has this bin been reported???

**Comment by remy** [comment]
We have an automated process which we're still fine tuning and frustratingly it does capture bins that are not worth of being parked.

However, I've flagged your account as good and none of your bins now can be trapped.

**Comment by AngerElf** [comment]
Brilliant, thanks

Den 14-08-2014 17:12, Remy Sharp skrev:
