### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by adamshaylor** [jsbin/reports#28]
Bin url: http://jsbin.com/getoru/2/edit

Perhaps someone thinks Angular’s $eval is the same thing as JavaScript’s native eval? (It’s not...)

http://stackoverflow.com/questions/15671471/angular-js-how-does-eval-work-and-why-is-it-different-from-vanilla-eval

**Comment by remy** [comment]
Fixed. Sorry that took a while!

**Comment by adamshaylor** [comment]
Thanks!
