### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by ProfessionalRidder** [jsbin/reports#37]
Bin url: http://jsbin.com/popoj/17/edit
I don't understand why my bin has been flagged as suspicious.
The only thing that i was doing, was programming a character maker for a play by post RPG (demnia), as they are pretty time consuming to make.
Luckily I do have a backup, but I would like to know why my bin has been reported, and know how to avoid it in the future.

**Comment by remy** [comment]
We have some automated tools for capturing bins, and it looks like yours got caught in the net incorrectly.

I've unflagged it and also flagged your account so your bins can't be flagged again - I hope that helps.
