### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by CapriKai88** [jsbin/reports#43]
Bin url: http://jsbin.com/fanaj/8

I have no idea as to why my bin has been reported. I'm just practicing writing code.

**Comment by remy** [comment]
That's fixed. We have some automated code to pick up junk bins, but it's not exactly perfect - which is why yours (incorrectly) got caught.

I've also changed your account so that you're flagged as a "goodie" and your bins can't be reported again. I hope that helps! :)

**Comment by CapriKai88** [comment]
Thanks Rem :)

On 28 August 2014 11:04, Remy Sharp notifications@github.com wrote:

> Closed #43 https://github.com/jsbin/reports/issues/43.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsbin/reports/issues/43#event-158319493.

## 

[image: -]
Kai
Free:Formers http://freeformers.com/

## Trainer by Day Awesome by Night

Tel: +44 (0)7972666357
Email: kai@freeformers.com
Facebook http://www.facebook.com/freeformers
 |
Twitter http://twitter.com/freeformers_uk
