### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by saintsal** [jsbin/reports#5]
Hi, this bin is part of web development course.  It's a student learning to use <img> tags in Sofia, Bulgaria.

Ping me at salim @ foundercentric.com is you hav any questions.  Thanks,
Sal

Bin url: http://jsbin.com/tuhequpixuku/1

**Comment by remy** [comment]
Fixed. Thanks for the report. If the bins are created using a (free) account, then I can flag your account to ensure this doesn't happen again.
