### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by ciel** [jsbin/reports#51]
Bin url: http://jsbin.com/focid/1/

I'm really confused as to why this would be reported. It's merely my tinkering with some expanded directives to plug into Kendo UI.

**Comment by remy** [comment]
We have an automated process that blocks bin, but it's far from perfect - as you saw! I've unblocked the bin, but also, I've flagged your jsbin account so that your bins can't be flagged by our systems again. I hope that helps.
