### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by lynxthelovedone** [jsbin/reports#54]
this bin shouldnt be reported... i'm not even finished making it!

Bin url: http://jsbin.com/mozuy/2/

**Comment by allouis** [comment]
i've unblocked that :)

**Comment by lynxthelovedone** [comment]
Thanks mate!

---

[image: -]
Lewie Allen
Free:Formers http://freeformers.com/

## Trainer/Social Media Coordinator/Web Developer

Tel: +44 (0)7707776757
Email: lewie@freeformers.com
Facebook http://www.facebook.com/freeformers
 |
Twitter http://twitter.com/freeformers_uk
