### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by gastonmorixe** [jsbin/reports#56]
Bin url: http://jsbin.com/kukamuyuluru/

**Comment by allouis** [comment]
This has been unblocked, and your user name has been flagged so we don't block your bins in future!

**Comment by gastonmorixe** [comment]
I experienced something very weird. I've got all the links reported instantly after sharing them  on facebook to some friend via private Messaging! Oo 

I remember months ago facebook was requiring a captcha everytime a link from jsbin was being shared (even privately). Now they report it! :( 

Thank you @allouis

**Comment by remy** [comment]
@imton can you send through a couple more example bins? 

We have some part automated process for doing the reporting, but obviously here it's going wrong.

**Comment by gastonmorixe** [comment]
@remy  any version of  http://jsbin.com/kukamuyuluru/ as soon as I shared them in facebook messages (I think 42, 41, 40) it was instantly (magically?) being blocked by you :(

**Comment by remy** [comment]
Okay, that's a bug. I'll look into it separately. I've also flagged your account (again - just in case!) so that url shouldn't get flagged (I've also unblocked 41, 42 and 43).

**Comment by gastonmorixe** [comment]
@remy thank you both :+1:

**Comment by JohnRDOrazio** [comment]
Funny I just tried sharing a simple bin in a facebook group to show a coding example (bin in question https://jsbin.com/xobeqedoca/edit?html,js,output), and facebook immediately blocked the post and wouldn't let me share it. Had me fill out a captcha, which I did, but that wasn't enough it got blocked anyways, and I was given the possibility to file a report. So I choose to file a report to ask them to whitelist jsbin.com as a trusted sandboxed code sharing / testing site but when I click submit on the report I get an error message popup saying "We could not process your request. Please try again later." How convenient. Is jsbin having problems with facebook? (rather, does facebook have problems with jsbin?)

**Comment by remy** [comment]
Facebook has problems with jsbin. I don't know why they've recently started
to block though.
