### ISSUE TITLE
Incorrectly reported bin (pdf.js usage examples)

### ISSUE THREAD

**Issue by samlh** [jsbin/reports#71]
Bin url: http://jsbin.com/pdfjs-helloworld-v2/9612/ and http://jsbin.com/pdfjs-prevnext-v2/6865/

Listed as examples of how to use pdf.js at https://github.com/mozilla/pdf.js#learning

Assuming pdf.js is not malicious (and it is bundled with firefox, so I expect it isn't), the bins are safe.

**Comment by remy** [comment]
Fixed!
