### ISSUE TITLE
Incorrectly reported bin

### ISSUE THREAD

**Issue by rmckeel** [jsbin/reports#89]
I'm not really sure why this is suspicious content.. it is a speed-reader I tested out in JavaScript. What happened?

Bin url: http://jsbin.com/qivikami/9/

**Comment by remy** [comment]
Sorry, this one slipped through the net. I've fixed it and green flagged the owner (rm - I'm guess this was you?).

**Comment by rmckeel** [comment]
Yes, that's me. Thank you!
